version: '3'

services:
  db:
    container_name: osoc-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev}
    volumes:
      - postgres:/data/db
  be:
    container_name: osoc-be
    build:
      context: ../
      dockerfile: ./docker/${DOCKERFILE:-Dockerfile}
    user: ${DOCKER_AS_USER}
    volumes:
      - ../:/src
    ports:
      - 8000:8000
    depends_on:
      - db
  redis:
    container_name: osoc-redis
    image: redis
    ports:
      - 6379:6379

volumes:
 postgres:
