# Generated by Django 3.2.12 on 2022-04-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Transgender'), ('3', 'Unknown')], default='3', max_length=1, verbose_name='gender'),
        ),
    ]
