# Generated by Django 4.0.3 on 2022-04-15 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='send date and time'),
        ),
    ]
