# Generated by Django 4.0.3 on 2022-03-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='student',
            name='suggestions',
            field=models.ManyToManyField(through='common.Suggestion', to='common.coach'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last email sent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coaches',
            field=models.ManyToManyField(blank=True, null=True, to='common.coach'),
        ),
    ]
