# Generated by Django 4.0.3 on 2022-03-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_coach_suggestions_student_suggestions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coaches',
            field=models.ManyToManyField(blank=True, to='common.coach'),
        ),
    ]
