# Generated by Django 3.2.12 on 2022-04-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsuggestion',
            unique_together=set(),
        ),
    ]
