# Generated by Django 3.2.13 on 2022-04-11 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_githubuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree_current_year',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='degree current year'),
        ),
        migrations.AddField(
            model_name='student',
            name='degree_duration',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='degree duration'),
        ),
        migrations.AddField(
            model_name='student',
            name='employment_agreement',
            field=models.CharField(default='', max_length=255, verbose_name='employment agreement'),
        ),
        migrations.AddField(
            model_name='student',
            name='english_rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='english rating'),
        ),
        migrations.AddField(
            model_name='student',
            name='fun_fact',
            field=models.TextField(default='', verbose_name='fun fact'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'FEMALE'), ('1', 'MALE'), ('2', 'TRANSGENDER'), ('3', 'UNKNOWN')], default='3', max_length=1, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='student',
            name='hinder_work',
            field=models.TextField(blank=True, null=True, verbose_name='hinder work'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last email sent'),
        ),
        migrations.AddField(
            model_name='student',
            name='pronouns',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='pronouns'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_coach',
            field=models.BooleanField(default=False, verbose_name='alum'),
        ),
        migrations.AlterField(
            model_name='student',
            name='call_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='call name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='extra info'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
