# Generated by Django 3.2.12 on 2022-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_projectsuggestion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('0', 'Applied'), ('1', 'Awaiting project'), ('2', 'Approved'), ('3', 'Contract confirmed'), ('4', 'Contract declined'), ('5', 'Rejected')], default='0', max_length=1, verbose_name='status'),
        ),
    ]
