# Generated by Django 3.2.12 on 2022-04-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_projectsuggestion_unique_together'),
        ('common', '0003_student_status'),
    ]

    operations = [
    ]
