# Generated by Django 3.2.12 on 2022-04-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_merge_20220420_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='final',
            field=models.BooleanField(default=False, verbose_name='final decision'),
        ),
        migrations.AlterField(
            model_name='projectsuggestion',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='suggestion',
            unique_together={('student', 'coach', 'final')},
        ),
    ]
