name: Deploy CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Verify production server
      run: |
        [[ -r ~/deploy.sh ]] || exit 1
    - name: "Deploy Application"
      run: |
        bash ~/deploy.sh
