name: Deploy CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Verify production server
      run: |
        [[ ! -r ~/deploy.sh ]] && echo "[-] Run action from production server!" && exit 1
      env:
    - name: "Deploy Application"
      run: |
        bash ~/deploy.sh
