name: Django CI

on:
  push:
    # branches:
    #   - main
    paths:
      - 'be/osoc/**/*.py'

jobs:
  django:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dev
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install Dependencies
      working-directory: ./be
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary
        pip install -r <(grep -v '^psycopg2' requirements.txt)
    - name: Build Django and run tests
      working-directory: ./be
      run: |
        python manage.py test
      env:
        POSTGRES_HOST: localhost
        REDIS_HOST: localhost
