name: Django CI

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - 'be/**/*.py'

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install Dependencies
      working-directory: ./be
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: ./be
      run: |
        python manage.py test
