name: Pylint CI

on:
  push:
    # branches:
    #   - main
    paths:
      - 'be/osoc/**/*.py'
jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      working-directory: ./be
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install psycopg2-binary
        pip install -r <(grep -v '^psycopg2' requirements.txt)
    - name: Analysing the code with pylint
      run: |
        pylint --max-line-length=255 $(git ls-files 'be/osoc/**/*.py' ':!:be/osoc/**/migrations/*.py')
