name: Vue CI

on:
  push:
    # branches:
    #   - main
    paths:
      - 'fe/src/**/*.js'
      - 'fe/src/**/*.ts'
      - 'fe/src/**/*.vue'
      - 'fe/tests/**/*.js'
      - 'fe/tests/**/*.ts'
      - 'fe/tests/**/*.vue'

jobs:
  vue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: ./fe
      run: |
        npm ci
    - name: Build Vue
      working-directory: ./fe
      run: |
        npm run build
    - name: Run tests
      working-directory: ./fe
      run: |
        npm run coverage
